@startuml

scale 650 width
skinparam monochrome true
skinparam BoxPadding 30
autonumber

== Fog Byggemarked ==

actor Customer as "Customer"
box "Presentation Layer"
boundary FrontController
control Servlet
end box

box "Logic Layer"
participant LF as "Facade"
end box
box "Storage Layer"
participant DM as "Mappers"
Database DB as "JDBC"
end box

Customer->FrontController: Input fra bruger
FrontController->Servlet: Behandler POST
Servlet->LF: Session Update
LF->DM: Database Kald
DM->DB: Prepared Statements,Con,SQL

DB-->o DM: SQL Exception
DM-->o LF: FogException
LF-->o Servlet: FogException
Servlet->Servlet: Catch FogException
Servlet-->FrontController: Forward Error
FrontController-->Customer: Error Besked

@enduml